blank_issues_enabled: true
contact_links:
  - name: Notesnook Discord Community
    url: https://discord.gg/6mHHyncHJE
    about: Reach out to us directly & discuss your issues, suggestions & other feedback!
