name: "Test @notesnook/core"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "packages/core/**"
  pull_request:
    types:
      - "ready_for_review"
      - "opened"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Prepare environment
        run: |
          npm install
      - name: Add environment variables
        run: |
          echo "EMAIL=${{ secrets.USER_EMAIL }}" >> $GITHUB_ENV
          echo "PASSWORD=${{ secrets.USER_PASSWORD }}" >> $GITHUB_ENV
          echo "HASHED_PASSWORD=${{ secrets.USER_HASHED_PASSWORD }}" >> $GITHUB_ENV
      - name: Run all @notesnook/core tests
        run: npx nx test:e2e @notesnook/core
