name: Publish @notesnook/ios

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-13
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: ./.github/actions/setup-node-with-cache

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}


      - name: Install node modules
        run: |
          npm ci --ignore-scripts --prefer-offline --no-audit
          npm run bootstrap -- --scope=mobile

      - name: Build packages
        run: npx nx run @notesnook/mobile:build
      
      - name: Setup ccache
        run: |
          brew install ccache
          ln -s $(which ccache) /usr/local/bin/gcc
          ln -s $(which ccache) /usr/local/bin/g++
          ln -s $(which ccache) /usr/local/bin/cc
          ln -s $(which ccache) /usr/local/bin/c++
          ln -s $(which ccache) /usr/local/bin/clang
          ln -s $(which ccache) /usr/local/bin/clang++
          export CCACHE_SLOPPINESS=clang_index_store,file_stat_matches,include_file_ctime,include_file_mtime,ivfsoverlay,pch_defines,modules,system_headers,time_macros
          export CCACHE_FILECLONE=true
          export CCACHE_DEPEND=true
          export CCACHE_INODECACHE=true
          export CCACHE_COMPILERCHECK=content

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.11
        with:
          key: ${{ runner.os }}-ccache-${{ hashFiles(format('apps/mobile/native/ios/Podfile.lock')) }}
          create-symlink: true
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Cache Pods
        uses: actions/cache@v2
        id: pods-cache
        with:
         path: apps/mobile/native/ios/Pods
         key: ${{ runner.os }}-pods-${{ hashFiles('apps/mobile/native/ios/Podfile.lock') }}

      - name: Install Pods
        run: npm run prepare:ios

      - name: Build iOS App
        uses: yukiarrr/ios-build-action@v1.11.2
        with:
          bundle-identifier: org.streetwriters.notesnook
          scheme: Notesnook
          configuration: "Release"
          export-options: apps/mobile/native/ios/ExportOptions.plist
          project-path: apps/mobile/native/ios/Notesnook.xcodeproj
          workspace-path: apps/mobile/native/ios/Notesnook.xcworkspace
          update-targets: |
            Notesnook
            Make Note
            NotesWidgetExtension
          disable-targets: Notesnook-tvOS,Notesnook-tvOSTests,NotesnookTests
          code-signing-identity: Apple Distribution
          team-id: ${{ secrets.APPLE_TEAM_ID }}
          p12-base64: ${{ secrets.APPLE_CERTIFICATE_P12 }}
          certificate-password: ${{ secrets.APPLE_CERTIFICATE_P12_PASSWORD }}
          app-store-connect-api-key-issuer-id: ${{ secrets.API_KEY_ISSUER_ID }}
          app-store-connect-api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
          app-store-connect-api-key-base64: ${{ secrets.APPSTORE_CONNECT_API_KEY_BASE64 }}
          output-path: Notesnook.ipa
          mobileprovision-base64: |
            ${{ secrets.APPLE_MOBILE_PROVISION_APP }}
            ${{ secrets.APPLE_MOBILE_PROVISION_SHARE }}
            ${{ secrets.APPLE_MOBILE_PROVISION_WIDGET }}

      # - name: 'Upload app to TestFlight'
      #   uses: apple-actions/upload-testflight-build@v1
      #   with: 
      #     app-path: Notesnook.ipa
      #     issuer-id: ${{ secrets.API_KEY_ISSUER_ID }}
      #     api-key-id: ${{ secrets.API_KEY_ID }}
      #     api-private-key: ${{ secrets.API_KEY }}

      # - name: Upload to Github
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Notesnook.ipa
      #     path: Notesnook.ipa
