name: Publish @notesnook/web Beta

on: 
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "apps/mobile/**"
      - "packages/editor-mobile/**"
      - "apps/desktop/**"
      - "apps/vericrypt/**"
      - "servers/**"
      - "packages/clipper/**"
      - "extensions/web-clipper/**"
  pull_request:
    types:
      - closed
      - ready_for_review
      - reopened
    branches:
      - master
    paths-ignore:
      - "apps/mobile/**"
      - "packages/editor-mobile/**"
      - "apps/desktop/**"
      - "apps/vericrypt/**"
      - "servers/**"
      - "packages/clipper/**"
      - "extensions/web-clipper/**"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/setup-node-with-cache

      - name: Install packages
        run: |
          npm ci --ignore-scripts --prefer-offline --no-audit
          npm run bootstrap -- --scope=web

      - name: Setup environment
        run: |
          echo "NX_CLOUD_ACCESS_TOKEN=${{ secrets.NX_CLOUD_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}" >> $GITHUB_ENV

      - name: Generate beta build
        run: npm run build:beta:web

      - name: Publish to Cloudflare Pages
        uses: unlike-ltd/github-actions-cloudflare-pages@v0.1.1
        id: pages
        with:
          cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          cloudflare-project-name: notesnook-beta-app
          directory: ./apps/web/build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-environment: ${{ (github.ref == 'refs/heads/master' && 'beta') || 'preview' }}
